export const cityOptions = [
  { value: "서울특별시", label: "서울특별시" },
  { value: "부산광역시", label: "부산광역시" },
];

export const guOptions = [
  { value: "종로구", label: "종로구", province: "서울특별시" },
  { value: "중구", label: "중구", province: "서울특별시" },
  { value: "용산구", label: "용산구", province: "서울특별시" },
  { value: "성동구", label: "성동구", province: "서울특별시" },
  { value: "광진구", label: "광진구", province: "서울특별시" },
  { value: "동대문구", label: "동대문구", province: "서울특별시" },
  { value: "중랑구", label: "중랑구", province: "서울특별시" },
  { value: "성북구", label: "성북구", province: "서울특별시" },
  { value: "강북구", label: "강북구", province: "서울특별시" },
  { value: "도봉구", label: "도봉구", province: "서울특별시" },
  { value: "노원구", label: "노원구", province: "서울특별시" },
  { value: "은평구", label: "은평구", province: "서울특별시" },
  { value: "서대문구", label: "서대문구", province: "서울특별시" },
  { value: "마포구", label: "마포구", province: "서울특별시" },
  { value: "양천구", label: "양천구", province: "서울특별시" },
  { value: "강서구", label: "강서구", province: "서울특별시" },
  { value: "구로구", label: "구로구", province: "서울특별시" },
  { value: "금천구", label: "금천구", province: "서울특별시" },
  { value: "영등포구", label: "영등포구", province: "서울특별시" },
  { value: "동작구", label: "동작구", province: "서울특별시" },
  { value: "관악구", label: "관악구", province: "서울특별시" },
  { value: "서초구", label: "서초구", province: "서울특별시" },
  { value: "강남구", label: "강남구", province: "서울특별시" },
  { value: "송파구", label: "송파구", province: "서울특별시" },
  { value: "강동구", label: "강동구", province: "서울특별시" },

  { value: "중구", label: "중구", province: "부산광역시" },
  { value: "서구", label: "서구", province: "부산광역시" },
  { value: "동구", label: "동구", province: "부산광역시" },
  { value: "영도구", label: "영도구", province: "부산광역시" },
  { value: "부산진구", label: "부산진구", province: "부산광역시" },
  { value: "동래구", label: "동래구", province: "부산광역시" },
  { value: "남구", label: "남구", province: "부산광역시" },
  { value: "북구", label: "북구", province: "부산광역시" },
  { value: "해운대구", label: "해운대구", province: "부산광역시" },
  { value: "사하구", label: "사하구", province: "부산광역시" },
  { value: "금정구", label: "금정구", province: "부산광역시" },
  { value: "강서구", label: "강서구", province: "부산광역시" },
  { value: "연제구", label: "연제구", province: "부산광역시" },
  { value: "수영구", label: "수영구", province: "부산광역시" },
  { value: "사상구", label: "사상구", province: "부산광역시" },
  { value: "기장구", label: "기장구", province: "부산광역시" },
];
